spring:
  datasource:
    url: jdbc:mysql://localhost:3307/onganimal
    username: dev
    password: 123
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
jwt:
  secret: Jjduhasuu2228sdah&7&@8sdjj