spring:
  datasource:
    url: jdbc:mysql://spvunyfm598dw67v.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/s5lbi8cbseijrits
    username: w61njuyj58mcgt8s
    password: cd548skks04xegg4
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
jwt:
  secret: Jjduhasuu2228sdah&7&@8sdjj