CREATE TABLE owner (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(11) NOT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE animal (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	owner_id BIGINT(20) NOT NULL,
	image MEDIUMBLOB,
	name VARCHAR(255) NOT NULL,
	age INT,
	extra_info VARCHAR(255),
	city VARCHAR(255) NOT NULL,
	state VARCHAR(255) NOT NULL,
	status VARCHAR(8) NOT NULL DEFAULT 'LOST',
	PRIMARY KEY(id),
	FOREIGN KEY (owner_id) REFERENCES owner(id) ON DELETE CASCADE
);

CREATE TABLE finded_animal (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	animal_id BIGINT(20) NOT NULL,
	name VARCHAR(255) NOT NULL,
	phone VARCHAR(255) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (animal_id) REFERENCES animal(id) ON DELETE CASCADE
);